title: Suraj Udasi
logo: /assets/img/surajudasi.jpg
description: MSc. Finance & Business Analytics | 7+ years of Corporate Finance and Strategy experience
show_downloads: True
theme: jekyll-theme-minimal
