title: Suraj Udasi
logo: /assets/img/surajudasi.jpg
description: MSc. Finance & Business Analytics | Over 7 years of Corporate Finance and Strategy experience | Retail, Consumer Product Goods, and Manufacturing industries
show_downloads: True
theme: jekyll-theme-minimal
