title: Suraj Udasi
logo: /assets/img/surajudasi.jpg
description: Over 7 years of Corporate Finance and Strategy experience, supporting executives in transactions valued over US$200 million across Retail, Consumer Product Goods, and Manufacturing industries by applying data-driven insights and effective communication.
show_downloads: True
theme: jekyll-theme-minimal
